[package]
name = "utils"
version = "0.1.0"
edition = "2024"

[dependencies]
etrace.workspace = true
typed-arena.workspace = true
toml.workspace = true
toml_edit.workspace = true
lazy_static.workspace = true

[package.metadata.rust-analyzer]
rustc_private = true
